Algoritmo "ex002 n001"
// Descrição   : ex002 n001
// Autor(a)    : Gabriel Menezes
// Data atual  : 07/03/20
Var
   n: inteiro

Inicio
   escreval ("insira número ")
   leia (n)
   se n mod 2 = 0 entao
      escreval ("número par")
   senao
      escreval ("número impar")
   fimse
   se n + 0 < 0 entao
      escreval ("número negativo")
   senao
      escreval ("número positivo")
   fimse



Fimalgoritmo